name: Manual Update

on:
  workflow_dispatch:

jobs:
  routine-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: npm install
      - run: node auto.js
      - run: |
          git config --global user.name 'addf0214'
          git config --global user.name 'slayerxj_reg@outlook.com'
          git commit -a -m "auto: manual update"
          git push
