name: Routine Update

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  routine-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2.5.2
      - run: npm install
      - run: node auto.js
      - run: |
          git config --global user.name 'addf0214'
          git config --global user.name 'addf0214@outlook.com'
          git commit -a -m "auto: routine update"
          git push
